alias getags="find ~/dev/q1/logic/ -name \"*.[chS]\" | xargs etags"
alias gctags="find ~/dev/q1/logic/ -name \"*.[chS]\" | xargs etags"
alias tf="tail -f"
alias rg="find . -name \"*\" | xargs grep "
alias rgc="find . -name \"*.[ch]\" | xargs grep "
alias rglog="find . -name \"*.log\" | xargs grep "
alias rgpy="find . -name \"*.py\" | xargs grep "
alias gr="grep -R * "
