alias emacsd="emacs --daemon"
alias emacs="emacs -nw"
alias xemacs="emacs"
alias ect="emacsclient -t -a emacs -nw"
alias ecc="emacsclient -c -a emacs -nw"
alias sect="sudo emacsclient -t -a emacs -nw"
alias secc="sudo emacsclient -c -a emacs -nw"
alias xect="emacsclient -t -a emacs"
alias xecc="emacsclient -c -a emacs"
alias sxect="sudo emacsclient -t -a emacs"
alias sxecc="sudo emacsclient -c -a emacs"

export PATH="$PATH:$HOME/.spacemacs.d/wowchan/xcscope"
alias gencs="cscope-indexer -r"
