# alias for git
alias gst="git status -s"
alias gff="git diff"
alias gco="git checkout"
alias gdd="git add"
alias gci="git commit"
alias gpl="git pull"
alias gpo="git push origin"
alias gbl="git blame"
alias gcp="git cherry-pick"
alias gss="git stash save"
alias gsp="git stash pop"
alias grd="git rebase develop"
alias grb="git rebase"
