[source]

[source.mirror]
registry = "https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index/"

[source.crates-io]
replace-with = "mirror"

[profile.dev]
debug = true
opt-level = 3
split-debuginfo = "unpacked"

[profile.test]
debug = true
opt-level = 3
split-debuginfo = "unpacked"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[profile.doc]
# panic = 'abort'