[source]

[source.mirror]
# registry = "https://mirrors.ustc.edu.cn/git/crates.io-index/"
registry = "https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index/"

[source.crates-io]
replace-with = "mirror"
